//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightClub.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        public int id { get; set; }
        public bool resolved { get; set; }
        public Nullable<int> result { get; set; }
        public int user1 { get; set; }
        public int user1move1 { get; set; }
        public int user1move2 { get; set; }
        public int user1move3 { get; set; }
        public int user2 { get; set; }
        public Nullable<int> user2move1 { get; set; }
        public Nullable<int> user2move2 { get; set; }
        public Nullable<int> user2move3 { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> solvedTime { get; set; }
        public Nullable<int> user1Points { get; set; }
        public Nullable<int> user2Points { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user3 { get; set; }
    }
}
