//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightClub.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.match = new HashSet<match>();
            this.match1 = new HashSet<match>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public int matchesLeft { get; set; }
        public int avatarId { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime lastModified { get; set; }
        public int score { get; set; }
        public int wins { get; set; }
        public int losses { get; set; }
    
        public virtual avatar avatar { get; set; }
        public virtual ICollection<match> match { get; set; }
        public virtual ICollection<match> match1 { get; set; }
    }
}
